#!/bin/sh


### single hashtype tester
BASEDIR="/home/marcin/hashes/crackall.git"
#DICTIONARIES="$BASEDIR/dicts/Really_Quick/*"
DICTIONARIES="$BASEDIR/dicts/Quick_Lists/*"
#DICTIONARIES="$BASEDIR/dicts/wordlists/*"
PASSWORDFILES="$BASEDIR/passwords/SSHA*.passwd"
JTRBIN="$BASEDIR/jtr/john"
SESSIONSDIR="$BASEDIR/sessions"
POTSDIR="$BASEDIR/pots"

for d in $DICTIONARIES
do
    for p in $PASSWORDFILES
    do
		FILENAME="john-wordlist-rulesstock-$(basename ${p})-$(basename ${d})"
		$JTRBIN \
			--wordlist=$d \
			--session="$SESSIONSDIR/$FILENAME" \
			--pot="$POTSDIR/$FILENAME" \
			--rules \
			--format=ssha \
			$p 
    done
done

# vim: noai:ts=4:sw=4
