#!/bin/sh


### single dictionary tester
BASEDIR="/home/marcin/hashes/crackall.git"
DICTIONARIES="$BASEDIR/dicts.bak/wikipedia"
PASSWORDFILES="$BASEDIR/passwords/*.passwd"
JTR="$BASEDIR/jtr/john"
SESSIONSDIR="$BASEDIR/sessions"
POTSDIR="$BASEDIR/pots"

for d in $DICTIONARIES
do
    for p in $PASSWORDFILES
    do

		$JTR \
		--wordlist=$d \
		--session="$SESSIONSDIR/john-wordlist-rulesstock-$(basename ${p})-$(basename ${d}.rec)" \
		--pot="$POTSDIR/john-wordlist-rulesstock-$(basename ${p})-$(basename ${d}.pot)" \
		$p

    done
done

# vim: noai:ts=4:sw=4
