#!/bin/sh

BASEDIR="/data"
DICTIONARIES="$BASEDIR/dicts/*"
PASSWORDFILES="$BASEDIR/passwords/*.passwd"
JTR="$BASEDIR/john-1.7.6-jumbo-12/run/john"
SESSIONFILES="$BASEDIR/sessions"
POTS="$BASEDIR/pots"
CDFS="$BASEDIR/CDFS"
GREP="/bin/grep"
AWK="/bin/awk"
STAT="/usr/bin/stat"
SYNC="/bin/sync"

declare -i count
count=0

for d in $DICTIONARIES
do
    for p in $PASSWORDFILES
    do
		FILENAME="john-wordlist$(basename ${p})-$(basename ${d})"
		INPUTFILE="$SESSIONFILES/${FILENAME}.log"	
		OUTPUTFILE="$CDFS/CDF-${FILENAME}.csv"

#		echo $count
		let count+=1
#		echo "Creating CDF file for $(basename $INPUTFILE)"
#		echo "...and writing it in  $(basename $OUTPUTFILE)"
### convert day:hr:min:sec to just seconds so it can be on an easy timescale
		$AWK -F: 'BEGIN {OFS=","}; /+ Cracked/ {print 24*60*60*$1+60*60*$2+60*$3+substr($4,1,2),++count}' $INPUTFILE > $OUTPUTFILE 

### remove empty files	
		if [ $(${STAT} -c%s $OUTPUTFILE) -eq 0 ]
		then
			rm -f $OUTPUTFILE
			let count-=1
		fi
    done
done

echo "$count useful logs analyzed."
$SYNC; $SYNC

# vim: noai:ts=4:sw=4
