#!/bin/bash
set -e 
set -x

### looks for 'Sessions aborted' log entry, finds their session and runs their .rec
source ./crackall.inc

#echo $DICTIONARIES
#echo $PASSWORDFILES

OLDDIR=$(pwd)
cd $SESSIONFILES
$GREP -l completed *.log > $COMPLETED
$GREP -l aborted *.log > $ABORTED
$COMM -23 $ABORTED $COMPLETED > $NOTDONE
cd $OLDDIR

### TODO:  gotta made DICTS and PASSWDS work differently so the restore job can access what it needs
for d in $DICTIONARIES
do
    for p in $PASSWORDFILES
    do
	   FILENAME="john-wordlist-rulesstock-$(basename ${p})-$(basename ${d})"
	   if [ $(grep -xc ${FILENAME}.log  $NOTDONE) -gt 0 ]
	   then
		  $JTR --restore=$SESSIONFILES/$FILENAME
	   fi
    done
done

set +x
set +e

# vim: noai:ts=4:sw=4
