#!/bin/sh
### single dictionary tester
BASEDIR="/data"
DICTIONARIES="$BASEDIR/dicts/*"
PASSWORDFILES="$BASEDIR/passwords/*.passwd"
JTRBIN="$BASEDIR/john-1.7.7-jumbo-1/run/john"
SESSIONSDIR="$BASEDIR/sessions"
POTSDIR="$BASEDIR/pots"
USER="root"

function johncount () { 	
	declare -i count
	declare -a pids
	pids=$(pgrep -u $USER john)
	count=${#pids[*]}
	echo $count
	return $count
}


declare -i NUMCPUS
NUMCPUS=4
until [ johncount -gt $NUMCPUS ] ; do
    for d in $DICTIONARIES
    do
	    for p in $PASSWORDFILES
		    do
			    FILENAME="john-singledict-$(basename ${p})-$(basename ${d})"
			    echo "### 5secs BEFORE new JtR"
			    johncount
			    sleep 5
		    
			    $JTRBIN \
				    --session="${SESSIONSDIR}/${FILENAME})" \
				    --pot="${POTSDIR}/${FILENAME}" \
				    --wordlist=$d \
				    --rules \
				    $p &
			    sleep 5
			    
			    echo "### 5secs AFTER new JtR"
			    johncount
		done	#for passwordfiles
    done	#for dictionaries
done	#until

# vim: smartindent:ts=2:sw=2
