#!/bin/sh


### single dictionary tester
BASEDIR="/home/marcin/hashes/crackall.git"
DICTIONARIES="$BASEDIR/dicts3/Dicts/Quick_Lists/*"
PASSWORDFILES="$BASEDIR/passwords/*.passwd"
JTRBIN="$BASEDIR/jtr/john"
SESSIONSDIR="$BASEDIR/sessions"
POTSDIR="$BASEDIR/pots"

for d in $DICTIONARIES
do
    for p in $PASSWORDFILES
    do
		FILENAME="john-wordlist-rulesstock-$(basename ${p})-$(basename ${d})"
		$JTRBIN \
			--wordlist=$d \
			--session="$SESSIONSDIR/$FILENAME" \
			--pot="$POTSDIR/$FILENAME" \
			--rules \
			$p 
    done
done

# vim: noai:ts=4:sw=4
