#!/bin/sh

BASEDIR="/data"
DICTIONARIES="$BASEDIR/dicts/*"
PASSWORDFILES="$BASEDIR/passwords/*.passwd"
JTR="$BASEDIR/john-1.7.6-jumbo-12/run/john"
SESSIONFILES="$BASEDIR/sessions"
POTS="$BASEDIR/pots"

#echo $DICTIONARIES
#echo $PASSWORDFILES

for d in $DICTIONARIES
do
    for p in $PASSWORDFILES
    do
	    $JTR -w:${d} \
		--rules \
		--pot=$POTS/john-wordlist-rulesstock-$(basename ${p})-$(basename ${d}) \
		--session=$SESSIONFILES/john-wordlist-rulesstock-$(basename ${p})-$(basename ${d}) \
		${p}
    done
done

# vim: noai:ts=4:sw=4
