#!/bin/sh


### single hashtype tester
BASEDIR="/home/marcin/hashes/crackall.git"
DICTIONARIES="$BASEDIR/dicts/Really_Quick/*"
#DICTIONARIES="$BASEDIR/dicts/wordlists/*"
#DICTIONARIES="$BASEDIR/dicts/Quick_Lists/*"
#DICTIONARIES="$BASEDIR/dicts/Large_Lists/*"
#DICTIONARIES="$BASEDIR/dicts/Alt_Lang/*"
PASSWORDFILES="$BASEDIR/passwords/somepass"
JTRBIN="$BASEDIR/john-1.7.7-jumbo-5/run/john"
SESSIONSDIR="$BASEDIR/sessions"
POTSDIR="$BASEDIR/pots"

for d in $DICTIONARIES
do
    for p in $PASSWORDFILES
    do
		if [ -f "${d}" ] 
		then
			FILENAME="john-rulessingle-$(basename ${p})"
			$JTRBIN \
				--wordlist=$d \
				--session="$SESSIONSDIR/$FILENAME" \
				--pot="$POTSDIR/$FILENAME" \
				--rules:single \
				--format=raw-md5 \
				$p 
		fi
    done
done

# vim: noai:ts=4:sw=4
