#!/bin/sh


### single hashtype tester
BASEDIR="/home/marcin/hashes/crackall.git"
#DICTIONARIES="$BASEDIR/dicts/Really_Quick/*"
#DICTIONARIES="$BASEDIR/dicts/Quick_Lists/*"
#DICTIONARIES="$BASEDIR/dicts/wordlists/*"
PASSWORDFILES="$BASEDIR/passwords/somepass.passwd
JTRBIN="$BASEDIR/john-1.7.7-jumbo-5/run/john"
SESSIONSDIR="$BASEDIR/sessions"
POTSDIR="$BASEDIR/pots"
FORMATS="lm nt ssha md5"

    for f in $FORMATS
    do
		FILENAME="john-onefile-$(basename ${f})"
		$JTRBIN \
			--session="$SESSIONSDIR/$FILENAME" \
			--pot="$POTSDIR/$FILENAME" \
			--format=${f} \
			$p 
    done

# vim: noai:ts=4:sw=4
