#!/bin/sh
function johncount () { 	
	declare -i count
	declare -a pids
	pids=$(pgrep -u marcin john)
	count=${#pids[*]}
	echo $count
	return $count
}

### single dictionary tester
BASEDIR="/home/marcin/hashes/crackall.git"
DICTIONARIES="$BASEDIR/dicts/*"
PASSWORDFILES="$BASEDIR/passwords/*.passwd"
JTRBIN="$BASEDIR/jtr/john"
SESSIONSDIR="$BASEDIR/sessions"
POTSDIR="$BASEDIR/pots"

declare -i NUMCPUS
NUMCPUS=4

for d in $DICTIONARIES
do
	for p in $PASSWORDFILES
		do
		until [ $(pgrep -u marcin john | wc -l ) -gt $NUMCPUS ] ; do
			echo "### 5secs BEFORE new JtR"
			johncount
		
			$JTRBIN \
				--session="$SESSIONSDIR/john-singledict-$(basename ${p})-$(basename ${d})" \
				--pot="$POTSDIR/john-singledict-$(basename ${p})-$(basename ${d})" \
				--wordlist=$d \
				--rules \
				$p &
			
			echo "### 5secs AFTER new JtR"
			johncount
		done	# until
    done	#for passwordfiles
done	#for dictionaries

# vim: smartindent:ts=2:sw=2
